version: "3.7"

services:
  chg-talis5-fe:
    # Build the image from the Dockerfile in the current directory
    build: .
    # Name of the container
    container_name: chg-talis5-fe
    # Restart the container always
    restart: always
    # Environment variables
    env_file:
      - .env
    # Expose the port
    ports:
      - "${PORT}:${PORT}"
